<a href="https://colab.research.google.com/github/prachimodi-142/MachineLearning/blob/main/Homework_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ex. 2 b.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import cvxpy as cp
import csv

# Load training data
train_cat = np.matrix(np.loadtxt('train_cat.txt', delimiter=','))
train_grass = np.matrix(np.loadtxt('train_grass.txt', delimiter=','))
Y = plt.imread('/content/cat_grass.jpg') / 255

# Compute sample mean for each class
mu1 = np.mean(train_cat, axis=1)
mu0 = np.mean(train_grass, axis=1)
print("mu 1 shape {}\n".format(mu1.shape))
print("mu 0 shape {}\n".format(mu0.shape))

# Compute sample covariance matrix for each class
Sigma1 = np.cov(train_cat)
Sigma0 = np.cov(train_grass)

# Compute priors
K1 = train_cat.shape[1]
K0 = train_grass.shape[1]
pi1 = K1 / (K1 + K0)
pi0 = K0 / (K1 + K0)

# Report results
print("mu1:", mu1[:, :2])
print("mu0:", mu0[:, :2])
print("Sigma1:\n", Sigma1[0, :2])
print("Sigma0:\n", Sigma0[0, :2])
print("pi1:", pi1)
print("pi0:", pi0)



In [ ]:
print("Sigma0:\n", Sigma0)
print("DET Sigma0:\n", np.linalg.det(Sigma0))

NameError: ignored

## Ex. 2 c.

In [ ]:
print("Sigma0:\n", Sigma0)
print("DET Sigma0:\n", np.linalg.det(Sigma0))
M,N = Y.shape
prediction = np.zeros([M,N])
sigma_1_inv = np.linalg.inv(Sigma1)
sigma_0_inv = np.linalg.inv(Sigma0)
sigma_1_det = np.linalg.det(Sigma1)
sigma_0_det = np.linalg.det(Sigma0)
print("sigma 1 inv = {}\n sigma 0 inv = {}".format(sigma_1_inv.shape, sigma_0_inv.shape))
for i in range(M-8):
  for j in range(N-8):
    block = Y[i:i+8, j:j+8].reshape(64,1)
    # print("block shape {}\n".format(block.shape))
    likelihood_1 = (-0.5 * (block - mu1).T @ sigma_1_inv @ (block - mu1) + np.log(pi1) - 0.5 * np.log(sigma_1_det))

    likelihood_0 = (-0.5 * (block - mu0).T @ sigma_0_inv @ (block - mu0) + np.log(pi0) - 0.5 * np.log(sigma_0_det))
    # print("likelihood 0 shape{}".format(likelihood_0.shape))
    # print("likelihood 2 shape{}".format(likelihood_1.shape))
    if likelihood_1 > likelihood_0:
      prediction[i,j] = 1
    else:
      prediction[i,j] = 0

      plt.imshow(Y)
      

Sigma0:
 [[0.064484   0.0369168  0.02382711 ... 0.02176124 0.02216335 0.02234282]
 [0.0369168  0.06623457 0.03760258 ... 0.02213225 0.02324899 0.02186965]
 [0.02382711 0.03760258 0.06663007 ... 0.0229264  0.02253505 0.02261312]
 ...
 [0.02176124 0.02213225 0.0229264  ... 0.06658705 0.0384956  0.02510532]
 [0.02216335 0.02324899 0.02253505 ... 0.0384956  0.06796744 0.03886852]
 [0.02234282 0.02186965 0.02261312 ... 0.02510532 0.03886852 0.06694585]]
DET Sigma0:
 3.5541573168672423e-91
sigma 1 inv = (64, 64)
 sigma 0 inv = (64, 64)
